### POST request to Create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Bennieiieieiei j",
  "email": "lol.popopop@exa.com",
  "address": "123 ben st",
  "dateOfBirth": "2000-09-09",
  "registeredDate": "2024-01-01"
}

###