### POST request to Create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John e",
  "email": "isabella.wker@exaple.com",
  "address": "123 Joh st",
  "dateOfBirth": "1999-09-09",
  "registeredDate": "2024-01-01"
}

###