### POST request to Create a new patient entity
POST http://lb-0b67d6c5.elb.localhost.localstack.cloud:4000/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Ben LocalStack",
  "email": "Local@jamin.com",
  "address": "123 Hoppa",
  "dateOfBirth": "2000-09-09",
  "registeredDate": "2024-01-01"
}

###