### PUT request to update an existing patient entity
PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174012
Content-Type: application/json

{
  "name": "Sophia C",
  "email": "sophia.clark@example.com",
  "address": "123 Hickory St, Shelbyville",
  "dateOfBirth": "1991-12-25"
}

###